# Generated by Django 3.1.4 on 2021-01-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('type', models.CharField(choices=[('f_n', 'Full name'), ('j', 'Job'), ('e', 'Email'), ('c_n', 'Company name'), ('i', 'Integer'), ('d', 'Date')], default='f_n', max_length=3)),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('range_from', models.PositiveIntegerField(blank=True, null=True)),
                ('range_to', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)')], default=',', max_length=1),
        ),
        migrations.AddField(
            model_name='schema',
            name='string_character',
            field=models.CharField(choices=[('"', 'Double quote (")'), ("'", "Single quote (')")], default='"', max_length=1),
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
