# Generated by Django 3.1.4 on 2021-01-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20210120_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(blank=True, choices=[('f_n', 'Full name'), ('j', 'Job'), ('e', 'Email'), ('c_n', 'Company name'), ('i', 'Integer'), ('d', 'Date')], default='f_n', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)')], default=',', max_length=1, verbose_name='Column separator'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='string_character',
            field=models.CharField(choices=[('"', 'Double quote (")'), ("'", "Single quote (')")], default='"', max_length=1, verbose_name='String character'),
        ),
    ]
