# Generated by Django 3.1.4 on 2021-01-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_column_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)')], max_length=1, verbose_name='Column separator'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='string_character',
            field=models.CharField(choices=[('"', 'Double quote (")'), ("'", "Single quote (')")], max_length=1, verbose_name='String character'),
        ),
    ]
