# Generated by Django 3.1.4 on 2021-01-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_auto_20210120_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('f_n', 'Full name'), ('j', 'Job'), ('e', 'Email'), ('c_n', 'Company name'), ('i', 'Integer'), ('d', 'Date')], default='f_n', max_length=3),
        ),
    ]
