# Generated by Django 3.1.4 on 2021-01-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_auto_20210126_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='status',
        ),
        migrations.AddField(
            model_name='dataset',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Dataset status'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='file',
            field=models.FileField(upload_to='', verbose_name='CSV file'),
        ),
    ]
